### PR TITLE
Enable istioctl build by Jenkins

### PR DESCRIPTION
**Pull request by sebastienvas**
- Update bin/push-docker to take multiple tags
- Re-enable istioctl builds as well as stable artifacts creation for release.

### CODE REVIEW

**Comment by sebastienvas** [comment]
@kyessenov For some reason the pilot e2e test is flaky from running in Prow https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/976/pilot-presubmit/157/. The only difference with Jenkins is the cluster we run from is using 1.6.4 instead of 1.6.0

**Comment by kyessenov** [comment]
Is there something running the cluster that's intefering?

**Comment by sebastienvas** [comment]
Maybe @nlandolfi. What should we look for  ?

**Comment by kyessenov** [comment]
I can't reproduce it. Seems to work fine on my cluster.

**Comment by kyessenov** [comment]
can this be closed now that jenkins is deprecated in pilot?

**Comment by sebastienvas** [comment]
This is still needed for the release and would rather keep while disabling
jobs in Jenkins for a little while.

**Comment by nlandolfi** [comment]
What needs to be done to move this to prow? Can I help?

**Comment by kyessenov** [comment]
Why do we need a separate job if post-submit can do this?

**Comment by sebastienvas** [comment]
Because this job is called from the release to just rebuild the artifacts. https://github.com/istio/istio/blob/master/release/README.md#rebuild-artifacts-to-include-the-tags

**Comment by sebastienvas** [comment]
@kyessenov, @rvkubiak is waiting for this to run manually through the release.

**Pull request merged**
