### PR TITLE
Add negative test for pilot

### PR DESCRIPTION
**Pull request by wattli**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wattli** [comment]
@kyessenov , please take a look.

**Comment by wattli** [comment]
@kyessenov , can you take a look?

**Comment by wattli** [comment]
@ijsnellf , @rkpagadala, could you help to merge this PR please? Thanks

**Comment by yutongz** [comment]
Can anyone with write access remove "do-not-merge" label? Robot added that label because of "release-note" missing, but would not auto remove it for safe concern.

**Comment by andraxylia** [comment]
This looks like it can be written to be part of the original for loop, without copy-pasting for the specific use case. I will remove the merge label if this is done correctly.

**Comment by wattli** [comment]
@andraxylia , please take a look, thanks

**Comment by wattli** [comment]
@andraxylia , can you help to remove the do-not-merge label? Thanks.

**Comment by kyessenov** [comment]
We still need tests for making sure that TLS connection with an invalid cert is not allowed.

**Comment by wattli** [comment]
Will do in a follow-up PR.

**Comment by yutongz** [comment]
/lgtm cancel 
For now, lgtm will be the only gate. To prevent accident merge, remove it for now.

**Comment by yutongz** [comment]
/test all
Do you know what is this, pilot test flaky?

**Comment by yutongz** [comment]
This pr is not properly tested before merged, bug from auto-merge mechanism.

**Comment by kyessenov** [comment]
Please disable mungegithub until this bug is solved. We should never merge PRs that fail to pass the tests.

**Comment by yutongz** [comment]
Disabled

**Pull request merged**
