### PR TITLE
Release 0.2 cherry pick cluster wide initializer

### PR DESCRIPTION
**Pull request by ayj**
**What this PR does / why we need it**:

Cherry-picks the following PR to make initializer cluster-wide in release-0.2 branch.

https://github.com/istio/pilot/pull/1437 - Added new parameter to exclude inject namespaces
https://github.com/istio/pilot/pull/1476 - bugfix: remove initializer when specific namespaces are set
https://github.com/istio/pilot/pull/1525 - Make initializer cluster wide

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
* Initializer now watches all namespaces and unconditionally removes itself from the list of pending initializers.
* Added new parameter to exclude inject namespaces. 
```

### CODE REVIEW

**Comment by gyliu513** [comment]
I confirm

**Comment by gyliu513** [comment]
@ayj do you know how to make cla happy?

**Comment by cmluciano** [comment]
@gyliu513 It looks like the git commit is referencing your gmail address. Is this the correct address that you signed the CLA with?

**Pull request merged**
