### PR TITLE
Cherry-picks from master

### PR DESCRIPTION
**Pull request by kyessenov**

### CODE REVIEW

**Comment by sebastienvas** [comment]
Jenkins job pilot/presubmit passed

**Comment by sebastienvas** [comment]
Jenkins job pilot/presubmit passed

**Comment by ldemailly** [comment]
so the difference between release-0.1 and master is absence of unary in 0.1 ?
(can this be seen through the github UI somehow ? or that the diff between the 2 is the same as the unary commit ?)

**Comment by kyessenov** [comment]
seems like it passed but status update is not working @sebastienvas

**Pull request merged**
