### PR TITLE
tracing: Provide a more meaningful service name in traces

### PR DESCRIPTION
**Pull request by objectiser**
**What this PR does / why we need it**:
Currently all trace spans generated by Istio proxied services are associated with the name 'istio-proxy'. This is confusing for end users, with the only indication of what services are being called, being the operation name which provides the hostname being called.

This PR enables the Deployment template's 'app' label value (if present) to be used as the service name.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: This PR outlines the issue as well as providing a potential fix.

**Special notes for your reviewer**:
The [istio service cluster configuration](https://github.com/istio/api/blob/master/proxy/v1/config/proxy_mesh.proto#L30-L42) comment seems to suggest that the reason a common 'istio-proxy' value is used, as Istio doesn't require a meaningful value to be able to do source caller routing. However this `service-cluster` value is also used by the tracing information produced by Envoy, to represent the service name.

The 'app' label has been selected, as it seems an appropriate single name that could be used by the proxy for a service name related to requests inbound/outbound of the potentially multiple containers within the deployment - but if a more appropriate source for a service name is available, then can be discussed.

A trace of the bookinfo example now looks like:

istio-jaeger

**Release note**:

```release-note
If the Deployment object within the kubernetes template includes an 'app' label, this value will be used as the service name associated with any tracing information generated via the proxy.
```

### CODE REVIEW

**Comment by objectiser** [comment]
@rshriram I see that issues are being reviewed ready for 0.2 release - any chance that this issue could be reviewed and possibly get into 0.2? I think it would be a good enhancement for the tracing information.

**Comment by rshriram** [comment]
Hey @objectiser this is cool.. I have been bugging @kyessenov a long time about fixing the istio-proxy value and we were thinking that we can encode the pod's service name (from service object) as the service cluster. However, that was a contentious topic, since one pod could belong to multiple services.. And the concept of using special environment variables also didn't seem to sit well. But the app label seems to be a nice compromise, given that common pattern is to use a deployment to manage a set of pods.
So, all in all, I am good with this.
cc @smawson - FYI. This seems like a nice solution to the service name problem. Though this may not cover all possible scenarios, it certainly cleans up the tracing issue.

**Pull request merged**
