### PR TITLE
platform, proxy: minor fixes/updates

### PR DESCRIPTION
**Pull request by odeke-em**
Noticed a few nits/improvements while familiarizing
myself with the code.

### CODE REVIEW

**Comment by kyessenov** [comment]
jenkins build pilot/presubmit

**Comment by kyessenov** [comment]
jenkins rebuild pilot/presubmit

**Comment by kyessenov** [comment]
Thanks! 
I've incorporated this PR into #852 since it would cause merge conflicts and jenkins doesn't seem to pick this one up for testing.

**Comment by odeke-em** [comment]
Thanks y'all for the review and merge!

**Pull request closed without merging**
