### PR TITLE
Change the default version used by kube-inject to be the full SHA

### PR DESCRIPTION
**Pull request by chxchx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by rshriram** [comment]
/retest
-- 

~shriram

**Comment by ldemailly** [comment]
wonder how we test this but... merging!

**Comment by ldemailly** [comment]
just realized it's still wrong:
```
        image: docker.io/istio/proxy_debug:330dd286541d1b84c5ac1f4fc504556796c070af
```
should be gcr.io/testing - or we should push to docker the postsubmit...

**Pull request merged**
