### PR TITLE
Ingress bug fixes

### PR DESCRIPTION
**Pull request by rshriram**
**What this PR does / why we need it**:
Some drive by bug fixes (attach port to the vhost so that requests with port can also be matched), use ingress instances when filtering routes, so that route rules can be scoped to ingress only.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/istio/issues/issues/87
https://github.com/istio/issues/issues/60

**Special notes for your reviewer**:

**Release note**:

```release-note
Ingress will allow port numbers in the authority header
```

### CODE REVIEW

**Comment by rshriram** [comment]
@markeijsermans @rfevang @maruina when this test passes, can you test with the Pilot image from this test to see if the port number issue is mitigated? (i.e. if your clients send foo.com:80, the ingress will accept it. [In the ingress resource, you can continue using the old `host: foo.com` format]

**Comment by rshriram** [comment]
This is the image: gcr.io/istio-testing/pilot:dc0d0e462a8db90d565c33eca9faa975e824ad40 (change istio.yaml to use this pilot image)

**Comment by rfevang** [comment]
Confirmed, hostname routing works using the given image.

**Comment by markeijsermans** [comment]
This fixes host routing issues. Paths are still problematic for grpc (see https://github.com/istio/issues/issues/87#issuecomment-334887649)

**Comment by rshriram** [comment]
do the *new* steps defined here help: https://istio.io/docs/tasks/traffic-management/ingress.html ? @markeijsermans @rfevang @maruina

**Pull request merged**
