### PR TITLE
Makefile: proper deps for the setup target

### PR DESCRIPTION
**Pull request by vbatts**
this config is linked, but not forcefully linked, during setup.

```
[vbatts@getdown] (master) ~/src/github.com/istio/pilot$ make
ln: failed to create symbolic link 'platform/kube/config': File exists
make: *** [Makefile:19: setup] Error 1
```

With this, a user could put their own config without getting clobbered,
or no error on `make` when the PHONY setup runs everytime.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
Thanks!

**Comment by vbatts** [comment]
these CI failures seem unrelated?

**Comment by kyessenov** [comment]
Excuse our extremely flaky e2e test :) It's like playing a lottery these days :)

**Comment by vbatts** [comment]
oh I see :-)

**Comment by kyessenov** [comment]
force merging, since this change is not even tested by CI :)

**Pull request merged**
