### PR TITLE
Support passthrough ports on the sidecar proxy

### PR DESCRIPTION
**Pull request by kyessenov**
Reference #474

### CODE REVIEW

**Review by ayj — APPROVED** [review]

**Comment by markvincze** [comment]
@kyessenov,
Do I see it correctly that this has only been released for `itio/proxy` and not `istio/proxy_debug`? If I try to use the `--passthrough` flag with `proxy_debug`, I get the error `unknown flag: --passthrough`.  
Isn't `proxy` and `proxy_debug` the same, just with different build config? (Sorry if this is described somewhere in the docs, I couldn't find any info about this with google.)

**Comment by markvincze** [comment]
@kyessenov Sorry, my bad. The difference is not between `proxy` and `proxy_debug`, but the version, because I was trying with `0.4.0` and `latest`.
So this flag is not present yet in `0.4.0`, and it'll come with the next release?

**Comment by rshriram** [comment]
We dont have this anymore, since we parse health check ports correctly,

**Comment by markvincze** [comment]
@rshriram,
You mean that if we have a setup like
```
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
...
  template:
    spec:
      containers:
      - name: my-service
        livenessProbe:
          httpGet:
            path: /status
            port: 5000
            scheme: HTTP
        ...
      - name: istio-proxy
        ...
```
Then the proxy should automatically pass through the port `5000`?

**Comment by emedina** [comment]
@rshriram This is still an issue in 0.4.0 without mTLS

@markvincze Have you make it work?

**Pull request merged**
