### PR TITLE
skip empty objects for the input files of istioctl commands

### LINKED ISSUE #1351: Istioctl: empty document section causes istioctl to issue errors
This issue is similar to fsstore2 complaining about `missing required keys` while parsing an empty section of configuration.

```
mjog@mjog0:~/GOHOME/src/istio.io/istio/tests$ cat > /tmp/bb.yaml
---
mjog@mjog0:~/GOHOME/src/istio.io/istio/tests$ istioctl create -f /tmp/bb.yaml 
Error: 1 error occurred:

* kind  is not known
```
This issue is related to https://github.com/istio/issues/issues/76.

### PR DESCRIPTION
**Pull request by jmuk**
**What this PR does / why we need it**:

Sometimes empty content can be in the input file(s) for istioctl and such empty config data can result in
errors, since istioctl doesn't know how to handle such data. They should be skipped.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1351

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by jmuk** [comment]
cc: @mandarjog

**Comment by jmuk** [comment]
Reviewers; the presubmit fails for unrelated files. Should I fix them too?

**Comment by kyessenov** [comment]
If tests pass locally, I can force merge. Linters are broken at the moment.

**Comment by jmuk** [comment]
The tests pass locally. The presubmit failed only for linters.
```
% bazel test //...
WARNING: /usr/local/google/home/mukai/.cache/bazel/_bazel_mukai/cf64fa9c8ef6fd7290cdb75b9774bc10/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:196:9: pkg_tar: renaming non-dict `files` attribute to `srcs`
INFO: Analysed 72 targets (0 packages loaded).
INFO: Found 54 targets and 18 test targets...
INFO: Elapsed time: 0.526s, Critical Path: 0.03s
INFO: Build completed successfully, 1 total action
//adapter/config/aggregate:go_default_xtest                     (cached) PASSED in 0.5s
//adapter/config/crd:go_default_test                            (cached) PASSED in 12.9s
//adapter/config/crd:go_default_xtest                           (cached) PASSED in 0.7s
//adapter/config/ingress:go_default_test                        (cached) PASSED in 31.3s
//adapter/config/memory:go_default_xtest                        (cached) PASSED in 0.6s
//adapter/serviceregistry/aggregate:go_default_test             (cached) PASSED in 0.6s
//model:go_default_test                                         (cached) PASSED in 0.2s
//model:go_default_xtest                                        (cached) PASSED in 0.4s
//platform/consul:go_default_test                               (cached) PASSED in 0.3s
//platform/eureka:go_default_test                               (cached) PASSED in 0.6s
//platform/kube/admit:go_default_test                           (cached) PASSED in 1.0s
//platform/kube:go_default_test                                 (cached) PASSED in 1.3s
//platform/kube/inject:go_default_test                          (cached) PASSED in 5.0s
//proxy/envoy:go_default_test                                   (cached) PASSED in 3.3s
//proxy:go_default_test                                         (cached) PASSED in 0.5s
//proxy:go_default_xtest                                        (cached) PASSED in 0.5s
//test/mock:go_default_test                                     (cached) PASSED in 0.6s
//tools/version:go_default_test                                 (cached) PASSED in 0.4s
```

**Comment by kyessenov** [comment]
Force merged. If this causes further problems, I'll fix it.

**Pull request merged**
