### PR TITLE
Recommend 1.7.5 for GKE and Minikube

### PR DESCRIPTION
**Pull request by ayj**
**What this PR does / why we need it**:

Recome

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by linsun** [comment]
is this a recommendation or requirement?  wanted to make sure it is not really a requirement else I'd like to know why.

**Comment by ayj** [comment]
Its a requirement for GKE since new clusters can only be created with 1.7.5, 1.6.9, or 1.6.7 (see https://cloud.google.com/container-engine/release-notes).

its a recommendation for Minikube so we use the latest patch release available.

**Comment by linsun** [comment]
ok thanks!  so istio itself doesn't have any hard requirement for 1.7.5 that you are aware of.

**Comment by ayj** [comment]
Correct

**Pull request merged**
