### PR TITLE
git ls-files|xargs sed -i .bak -e 's/PullPolicy: Always/PullPolicy: IfNotPresent/g'

### PR DESCRIPTION
**Pull request by ldemailly**
Fixes https://github.com/istio/istio/issues/441

(Manual adjustments to not touch files where trailing newline is
missing + manual change of go file)

### CODE REVIEW

**Comment by ldemailly** [comment]
@kyessenov can you please (force) merge this ? TIA !

**Comment by kyessenov** [comment]
Do we know why e2e smoketest fails?

**Comment by kyessenov** [comment]
For future reference, run `env REFRESH_GOLDEN=true go test istio.io/pilot/platform/kube/inject/...` to automatically refresh golden artifacts.

**Comment by ldemailly** [comment]
doesn't look like a new failure is it ?
ie the usual
W0803 02:37:21.074] E0803 02:37:21.072824    5212 demo_test.go:144] Couldn't get to the bookinfo product page, trying again in 50 second


cf https://github.com/istio/istio/issues/537

**Pull request merged**
