### PR TITLE
Use regex field instead of overloading header match for regex routes

### PR DESCRIPTION
**Pull request by rshriram**
**What this PR does / why we need it**:
We currently use header match for regex matching of routes. Instead, switch to the regex field introduced as a first class entity in Envoy config.
In addition, this PR uses prefix based matching for Ingress paths, instead of exact path based matches, as most users are used to the standard nginx ingress behavior (prefix match) [most people using istio ingress were confused as to why things didn't work]

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Istio ingress defaults to prefix based URL match, similar to Kubernetes ingress.
```

Do not merge until Proxy sha is updated.

### CODE REVIEW

**Comment by kyessenov** [comment]
What happened to two approvals?

**Comment by kyessenov** [comment]
This doesn't work for combining ingress and route rules.
If I create a rule saying to route to version v2 if route matches certain regex, the rule will be ignored. Please follow-up with a fix or revert.

K8s spec requires path to be a regex. Nginx does not follow the spec, so we should not follow the spec, too, in your opinion?

**Comment by rshriram** [comment]
A subsequent PR will resolve the combination issue between ingress rule and route rules.

**Comment by ldemailly** [comment]
we need TWO reviews before making significant changes

**Pull request merged**
