### PR TITLE
kube-inject: add support for StatefulSets

### PR DESCRIPTION
**Pull request by kelseyhightower**
This change add support for StatefulSet to the kube-inject command.

### CODE REVIEW

**Comment by kelseyhightower** [comment]
Look like we need to update the `k8s.io/client-go` package. The change causes the following build error:

```
platform/kube/inject/inject.go:38: can't find import: "k8s.io/client-go/pkg/apis/apps/v1beta1"
```

**Comment by kyessenov** [comment]
Thanks, Kelsey. The build error is probably due to bazel BUILD dependency declaration. You can try to add it yourself (`bin/gazelle` tool) or just let me patch it up for you.

**Comment by kelseyhightower** [comment]
@kyessenov I've updated the dependencies and tests PTAL.

**Comment by rshriram** [comment]
build pilot/presubmit

**Comment by rshriram** [comment]
jenkins rebuild pilot/presubmit

**Comment by rshriram** [comment]
fixes https://github.com/istio/issues/issues/28

**Comment by ijsnellf** [comment]
build pilot/presubmit

**Comment by rshriram** [comment]
@kyessenov what do we do about the stuck Jenkins?

**Comment by ldemailly** [comment]
@rshiram you need to add kesley to the org for jenkins to trigger
(i already filled an issue w seb about that a while back, this is the current workaround)

**Comment by rshriram** [comment]
build pilot/presubmit

**Comment by rshriram** [comment]
@kelseyhightower pardon our Jenkins mess :(. We really need this bug fix. Would you mind if I forked your branch, and submitted this PR from my user ID? (commits will still be under your name). Jenkins refuses to build PRs from folks outside Istio org. And we simply can't keep adding all contributors to istio org. 

If you happen to have an alternate solution, I am all ears. :).

**Comment by ldemailly** [comment]
Well we can add Kesley

**Comment by rshriram** [comment]
tried and it didn't work. He is already marked as a collaborator for the project

**Comment by ldemailly** [comment]
build pilot/presubmit

**Comment by ldemailly** [comment]
build pilot/presubmit
build manager/presubmit

**Comment by ldemailly** [comment]
@sebastienvas : this is odd, the pr log 
https://testing.istio.io/job/pilot/job/presubmit/github-pr-polling/
just shows
```
PR [#896 kube-inject: add support for StatefulSets] not changed
Finished GitHub Pull Request trigger check for GitHubRepositoryName[host=github.com,username=istio,repository=pilot] at Jul 6, 2017 6:27:55 PM. Duration: 246ms
```
any idea why it's not triggering ?

**Comment by sebastienvas** [comment]
build pilot/presubmit

**Comment by sebastienvas** [comment]
@kelseyhightower I just sent you a invite to be a member. Could you please accept it ?

**Comment by rshriram** [comment]
build pilot/presubmit

**Comment by rshriram** [comment]
YAY!! Finally, jenkins is running

**Comment by rshriram** [comment]
@kelseyhightower linter errors
```platform/kube/inject/inject.go:1::warning: file is not gofmted with -s (gofmt)
platform/kube/inject/inject.go:1::warning: file is not goimported (goimports)```

**Pull request merged**
