### PR TITLE
use cloud.google.com instead of www.google.com in egress test

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
**What this PR does / why we need it**:
in countries other than US, www.google.com redirects to local versions
of google e.g. www.google.co.il, www.google.de etc.

**Which issue this PR fixes** *(optional, in `fixes 

this redirection fails the egress test. cloud.google.com does not redirect and works OK outside of US

#<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by rshriram** [comment]
This should not even access anything.. Is it actually accessing www.google.com ? If so, we can revert to simple httpbin.org

**Comment by vadimeisenbergibm** [comment]
@rshriram it does accesses httbin.org and www.google.com and expects to receive 200 status code. In countries outside of US, request to www.google.com, will return 302 with redirection to local google site and the test will fail.

**Comment by ijsnellf** [comment]
I think @rshriram was suggesting using https://httpbin.org instead of google.

**Comment by vadimeisenbergibm** [comment]
@ijsnellf The test currently tests both httbin.org and google.com. I think it is a good idea to check more than external site.

**Pull request merged**
