### PR TITLE
added sidecar command to proxy command

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixing https://github.com/istio/pilot/issues/1083.

**Special notes for your reviewer**:

**Release note**:

```release-note-none
```

### CODE REVIEW

**Comment by linsun** [comment]
@vadimeisenbergibm - could you briefly explain what is the user benefit of this?  why would a user choose sidecar arg?  Any user impact in the docs?  many thanks!

**Comment by linsun** [comment]
Reading #1083, seems this is not exposed to the user? can you confirm that?

**Comment by kyessenov** [comment]
It is not exposed to the user, and is closer to how 0.1 worked.

**Comment by vadimeisenbergibm** [comment]
@linsun it is a bug, the sidecar envoys will not start since they will receive wrong arguments.

**Comment by linsun** [comment]
yep, got it, after reviewing your changes.  Thank you @kyessenov and @vadimeisenbergibm for confirming that. :)

**Pull request merged**
