### PR TITLE
Remove race test

### PR DESCRIPTION
**Pull request by kyessenov**
Important tests already run in parallel with `t.Parallel`.

### CODE REVIEW

**Comment by kyessenov** [comment]
fixes #876

**Comment by ldemailly** [comment]
build pilot/presubmit

**Comment by ldemailly** [comment]
(hope we won't regret not having the race test - should that be done at least weekly or some such?)

**Comment by kyessenov** [comment]
go race test is quite naive. it simply spawns tests in parallel and tries to catch unprotected writes. since our unit tests allocate resources (namespaces) this native approach is harmful as it generates  a lot of load on the cluster.

**Pull request merged**
