### PR TITLE
Fix the bug that when no service account is specified in annotation, empty service accounts are returned.

### PR DESCRIPTION
**Pull request by myidpt**
```
NONE
```

### CODE REVIEW

**Comment by myidpt** [comment]
@wattli PTAL. Thanks!

**Comment by ldemailly** [comment]
what's the desired behavior when there is no annotation ? which service account is used?
cc @costinm we were just talking about this

**Comment by myidpt** [comment]
@ldemailly @costinm 
The annotation is to mark the service accounts that run the service on VMs. Note that the service can be run by Kubernetes pods, in which case the pods' service accounts do not need to be annotated (since this info can be retrieved from apiserver).
So if the annotation is empty, the service may still be run by the K8s pods. And the secure naming info is a mapping from the service to the pods' service accounts.

**Comment by wattli** [comment]
Sorry for the late response, good work, thanks!

**Pull request merged**
