### PR TITLE
Update pilot-coverage.sh

### PR DESCRIPTION
**Pull request by kyessenov**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by sebastienvas** [comment]
Wait I need to update the prow config to set the cluster. We skip report, do we want to enable it back?

**Comment by kyessenov** [comment]
Not sure what you mean by "skip report"

**Comment by sebastienvas** [comment]
https://github.com/istio/test-infra/blob/master/prow/config.yaml#L623

It means that it does not report back to the PR. As you can see, it is not listed in the checks.

**Comment by kyessenov** [comment]
That's fine. I think we can run coverage locally. We just want to keep the statistics over time.

**Pull request merged**
